services:  
  pilot:
    git_url: https://github.com/cloud66-samples/pilot.git
    git_branch: master
    ports:
    - container: 8050
      http: 80
      https: 443
    command: "/go/src/app/app --port=8050 --dport=8051 --dip=zigot1.sampler"
  zigot1:
    git_url: https://github.com/cloud66-samples/pilot.git
    git_branch: master
    ports:
    - container: 8051
      http: 8080
      https: 8443  
    command: "/go/src/app/app --port=8051 --dport=8050 --dip=pilot.sampler"
